### ISSUE TITLE
请问在python2里怎么改spiders.py的问题

### ISSUE THREAD

**Issue by youngjeff** [caoxiaozh/itjuzi_dis#2]
您在博客中说
```
特别要说明的是COPY spiders.py /usr/local/lib/python3.5/site-packages/scrapy_redis，将 host 中的 spiders.py 拷贝到container 中的 scrapy_redis 安装目录中，因为 lpop 获取redis 的值在 python2中是 str 类型，而在 python3中是 bytes 类型，这个问题在 scrapy_reids 中需要修复，spiders.py 第84行需要修改；
```
请问应该怎么改，可以说一下吗？

**Comment by hardy4yooz** [comment]
从
req = self.make_request_from_data(data)
到
req = self.make_request_from_data(data.decode('utf-8'))

**Comment by youngjeff** [comment]
我运行docker-compose up,出现下面的问题：
![qq 20170502203851](http://7xjj3y.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170502203851.png)

**Comment by youngjeff** [comment]
我在运行docker-compose up ，出现了下面的问题：
![](http://7xjj3y.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170502203851.png)

**Comment by hardy4yooz** [comment]
已回复。

**Comment by hardy4yooz** [comment]
CMD /usr/local/bin/scrapy crawl itjuzi_dis  
应该是这里的命令失败了，你进入容器内部 执行以下试试。
是不是 scrapy 版本原因或者是路径错误导致了crawl 无效。

**Comment by youngjeff** [comment]
我进入容器内没有报错，但是使用docker-compose up会出错，我在一台ubuntu上运行整个系统都没问题，在我自己的centos上运行一直报错，scrapy no active project，不知道为什么？

**Comment by hardy4yooz** [comment]
你的意思是在 ubuntu 上使用 docker compose 不会报错？
在 centos 上就报错是吗？

**Comment by youngjeff** [comment]
是的

**Comment by hardy4yooz** [comment]
你把所有的配置都放进一个 docker image里，然后直接 load 到 centos 里呢？

**Comment by youngjeff** [comment]
我试试

**Comment by youngjeff** [comment]
程序可以运行起来了，但是出现了其他的问题
![image](https://cloud.githubusercontent.com/assets/9778384/25732527/3caaa256-3183-11e7-89a1-b0a27d63c2d0.png)

**Comment by hardy4yooz** [comment]
这个有可能是因为 IT 桔子已经修改了页面内容了。所有你需要自己去匹配页面的正则表达式。

**Comment by youngjeff** [comment]
程序可以跑起来，但是爬了十几条数据就出现了这样问题：
![image](https://cloud.githubusercontent.com/assets/9778384/26030682/154e565c-388c-11e7-8d82-37fa0161a03b.png)

**Comment by hardy4yooz** [comment]
现在正常了吗？
