### ISSUE TITLE
运行的时候出现了问题

### ISSUE THREAD

**Issue by youngjeff** [caoxiaozh/itjuzi_dis#3]
使用 docker-compose up ，爬虫无法正常运行，并报出了如下的问题：

![](http://7xjs0i.com1.z0.glb.clouddn.com/2.png)

**Comment by hardy4yooz** [comment]
你进入 docker 容器内部 执行以下命令试试，提示 crawl 命令不存在，难道是 scrapy 版本不一致导致的？

**Comment by youngjeff** [comment]
代码我改好，但是redis想用其他地方的，而不是localhost，应该怎么操作，谢谢了
